{% set version = '2.4.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-azurermr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AzureRMR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AzureRMR/AzureRMR_{{ version }}.tar.gz
  sha256: 810e8f290bd4a94c4cfb755ccc4c44da0a716d1db36b0f1d114e9a267a7fd01c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-azureauth >=1.2.1
    - r-azuregraph >=1.2.0
    - r-r6
    - r-httr >=1.3
    - r-jsonlite
    - r-uuid
  run:
    - r-base
    - r-azureauth >=1.2.1
    - r-azuregraph >=1.2.0
    - r-r6
    - r-httr >=1.3
    - r-jsonlite
    - r-uuid

test:
  commands:
    - $R -e "library('AzureRMR')"           # [not win]
    - "\"%R%\" -e \"library('AzureRMR')\""  # [win]

about:
  home: https://github.com/Azure/AzureRMR https://github.com/Azure/AzureR
  license: MIT
  summary: A lightweight but powerful R interface to the 'Azure Resource Manager' REST API. The
    package exposes a comprehensive class framework and related tools for creating,
    updating and deleting 'Azure' resource groups, resources and templates. While 'AzureRMR'
    can be used to manage any 'Azure' service, it can also be extended by other packages
    to provide extra functionality for specific services. Part of the 'AzureR' family
    of packages.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: AzureRMR
# Title: Interface to 'Azure Resource Manager'
# Version: 2.4.3
# Authors@R: c( person("Hong", "Ooi", , "hongooi73@gmail.com", role = c("aut", "cre")), person("Microsoft", role="cph") )
# Description: A lightweight but powerful R interface to the 'Azure Resource Manager' REST API. The package exposes a comprehensive class framework and related tools for creating, updating and deleting 'Azure' resource groups, resources and templates. While 'AzureRMR' can be used to manage any 'Azure' service, it can also be extended by other packages to provide extra functionality for specific services. Part of the 'AzureR' family of packages.
# URL: https://github.com/Azure/AzureRMR https://github.com/Azure/AzureR
# BugReports: https://github.com/Azure/AzureRMR/issues
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# Depends: R (>= 3.3)
# Imports: AzureGraph (>= 1.2.0), AzureAuth (>= 1.2.1), utils, parallel, httr (>= 1.3), jsonlite, R6, uuid
# Suggests: knitr, rmarkdown, testthat, httpuv, AzureStor
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-10-23 04:54:48 UTC; hongo
# Author: Hong Ooi [aut, cre], Microsoft [cph]
# Maintainer: Hong Ooi <hongooi73@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-10-23 05:30:02 UTC
